LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := openCVLibrary344
LOCAL_LDFLAGS := -Wl,--build-id
LOCAL_SRC_FILES := \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv\cv.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv\cvaux.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv\cxcore.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv\cxeigen.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\calib3d\calib3d.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\calib3d.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\affine.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\base.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\bindings_utils.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\bufferpool.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\check.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\core.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\block.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\border_interpolate.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\color.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\common.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\datamov_utils.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\detail\color_detail.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\detail\reduce.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\detail\reduce_key_val.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\detail\transform_detail.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\detail\type_traits_detail.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\detail\vec_distance_detail.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\dynamic_smem.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\emulation.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\filters.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\funcattrib.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\functional.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\limits.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\reduce.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\saturate_cast.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\scan.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\simd_functions.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\transform.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\type_traits.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\utility.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\vec_distance.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\vec_math.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\vec_traits.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\warp.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\warp_reduce.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda\warp_shuffle.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda.inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda_stream_accessor.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cuda_types.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cvstd.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\cvstd.inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\directx.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\eigen.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\fast_math.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\hal.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\intrin.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\intrin_avx.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\intrin_cpp.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\intrin_forward.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\intrin_neon.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\intrin_sse.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\intrin_sse_em.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\hal\intrin_vsx.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\ippasync.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\mat.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\mat.inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\matx.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\neon_utils.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\ocl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\ocl_genbase.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\ocl_defs.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\opencl_info.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\opencl_svm.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\autogenerated\opencl_clamdblas.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\autogenerated\opencl_clamdfft.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\autogenerated\opencl_core.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\autogenerated\opencl_core_wrappers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\autogenerated\opencl_gl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\autogenerated\opencl_gl_wrappers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_clamdblas.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_clamdfft.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_core.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_core_wrappers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_gl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_gl_wrappers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_svm_20.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_svm_definitions.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opencl\runtime\opencl_svm_hsa_extension.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\opengl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\operations.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\optim.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\ovx.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\persistence.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\ptr.inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\saturate.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\softfloat.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\sse_utils.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\traits.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\types.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\utility.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\utils\filesystem.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\utils\logger.defines.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\utils\logger.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\utils\trace.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\va_intel.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\version.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\vsx_utils.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core\wimage.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\core.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\dnn\all_layers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\dnn\dict.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\dnn\dnn.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\dnn\dnn.inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\dnn\layer.details.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\dnn\layer.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\dnn\shape_utils.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\dnn.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\features2d\features2d.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\features2d.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\flann\flann.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\flann\flann_base.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\flann\miniflann.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\flann.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\highgui\highgui.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\highgui.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\imgcodecs\imgcodecs.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\imgcodecs.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\imgproc\detail\distortion_model.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\imgproc\hal\hal.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\imgproc\imgproc.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\imgproc.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\ml\ml.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\ml\ml.inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\ml.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\objdetect\detection_based_tracker.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\objdetect\objdetect.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\objdetect.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\opencv.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\opencv_modules.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\photo\cuda.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\photo\photo.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\photo.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\shape\emdL1.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\shape\hist_cost.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\shape\shape.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\shape\shape_distance.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\shape\shape_transformer.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\shape.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\autocalib.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\blenders.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\camera.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\exposure_compensate.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\matchers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\motion_estimators.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\seam_finders.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\timelapsers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\util.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\util_inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\warpers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\detail\warpers_inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching\warpers.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\stitching.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\superres\optical_flow.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\superres.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\video\background_segm.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\video\tracking.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\video\video.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\video.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videoio\registry.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videoio\videoio.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videoio.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\deblurring.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\fast_marching.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\fast_marching_inl.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\frame_source.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\global_motion.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\inpainting.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\log.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\motion_core.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\motion_stabilizing.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\optical_flow.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\outlier_rejection.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\ring_buffer.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\stabilizer.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab\wobble_suppression.hpp \
	F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include\opencv2\videostab.hpp \

LOCAL_C_INCLUDES += F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\debug\jni
LOCAL_C_INCLUDES += F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\main\jni
LOCAL_C_INCLUDES += F:\Android_Projects\MotionTrackingAndroid\openCVLibrary344\src\sdk\native\jni\include

include $(BUILD_SHARED_LIBRARY)
