/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
#include <opencv2/tracking.hpp>
#include <opencv2/core/ocl.hpp>
/* Header for class com_bd_shuyu_motiontrackingandroid_OpencvNativeObjectTracker */

using namespace cv;
using namespace std;
#ifndef _Included_com_bd_shuyu_motiontrackingandroid_OpencvNativeObjectTracker
#define _Included_com_bd_shuyu_motiontrackingandroid_OpencvNativeObjectTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bd_shuyu_motiontrackingandroid_OpencvNativeObjectTracker
 * Method:    objectTracker
 * Signature: (J)I
 */

 int track(Mat& frame);
JNIEXPORT jint JNICALL Java_com_bd_shuyu_motiontrackingandroid_OpencvNativeObjectTracker_objectTracker
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
