/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bd_shuyu_motiontrackingandroid_JniTest */

#ifndef _Included_com_bd_shuyu_motiontrackingandroid_JniTest
#define _Included_com_bd_shuyu_motiontrackingandroid_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bd_shuyu_motiontrackingandroid_JniTest
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bd_shuyu_motiontrackingandroid_JniTest_getMessageFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
