/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
/* Header for class com_bd_shuyu_motiontrackingandroid_OpencvNatives_OpencvNativeFaceDetection */

using namespace cv;
#ifndef _Included_com_bd_shuyu_motiontrackingandroid_OpencvNatives_OpencvNativeFaceDetection
#define _Included_com_bd_shuyu_motiontrackingandroid_OpencvNatives_OpencvNativeFaceDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bd_shuyu_motiontrackingandroid_OpencvNatives_OpencvNativeFaceDetection
 * Method:    faceDetection
 * Signature: (J)I
 */
 int detect(Mat& frame);
JNIEXPORT jint JNICALL Java_com_bd_shuyu_motiontrackingandroid_OpencvNatives_OpencvNativeFaceDetection_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
