/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
/* Header for class com_bd_shuyu_motiontrackingandroid_OpencvNativeCls */

using namespace cv;
using namespace std;
#ifndef _Included_com_bd_shuyu_motiontrackingandroid_OpencvNativeCls
#define _Included_com_bd_shuyu_motiontrackingandroid_OpencvNativeCls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bd_shuyu_motiontrackingandroid_OpencvNativeCls
 * Method:    cvtGray
 * Signature: (JJ)I
 */
 int toGray(Mat img, Mat& gray);

JNIEXPORT jint JNICALL Java_com_bd_shuyu_motiontrackingandroid_OpencvNativeCls_cvtGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
