/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_bd_shuyu_motiontrackingandroid_OpencvNativeObjectTracker.h"
/* Header for class com_bd_shuyu_motiontrackingandroid_OpencvNativeObjectTracker */

JNIEXPORT jint JNICALL Java_com_bd_shuyu_motiontrackingandroid_OpencvNativeObjectTracker_objectTracker
  (JNIEnv *, jclass, jlong addrRgba) {

    Mat& frame = *(Mat*)addrRgba;

    int retVal = track(frame);

    return (jint) retVal;
  }

int track(Mat& frame){

      string trackerTypes[8] = {"BOOSTING", "MIL", "KCF", "TLD","MEDIANFLOW", "GOTURN", "MOSSE", "CSRT"};
      // vector <string> trackerTypes(types, std::end(types));

      // Create a tracker
      string trackerType = trackerTypes[2];

      Ptr<Tracker> tracker;

      #if (CV_MINOR_VERSION < 3)
      {
          tracker = Tracker::create(trackerType);
      }
      #else
      {
          if (trackerType == "BOOSTING")
              tracker = TrackerBoosting::create();
          if (trackerType == "MIL")
              tracker = TrackerMIL::create();
          if (trackerType == "KCF")
              tracker = TrackerKCF::create();
          if (trackerType == "TLD")
              tracker = TrackerTLD::create();
          if (trackerType == "MEDIANFLOW")
              tracker = TrackerMedianFlow::create();
          if (trackerType == "GOTURN")
              tracker = TrackerGOTURN::create();
          if (trackerType == "MOSSE")
              tracker = TrackerMOSSE::create();
          if (trackerType == "CSRT")
              tracker = TrackerCSRT::create();
      }
      #endif

      Rect2d bbox(287, 23, 86, 320);



}